apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        group: frontend
      containers:
        - name: frontend
          image: DOCKER_IMAGE
          ports:
            - containerPort: 80
      restartPolicy: Always
